2018-10-27 14:13:28,755 INFO Save directory: C:\Users\Julian\GitHub\TEDx-YTT
2018-10-27 14:13:28,758 WARNING file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "C:\Users\Julian\Anaconda3\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Julian\Anaconda3\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Julian\Anaconda3\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Julian\Anaconda3\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 41, in autodetect
    from . import file_cache
  File "C:\Users\Julian\Anaconda3\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
2018-10-27 14:13:28,759 INFO URL being requested: GET https://www.googleapis.com/discovery/v1/apis/youtube/v3/rest
2018-10-27 14:13:30,219 INFO TRACE: Calling load_data() with ('C:\\Users\\Julian\\GitHub\\TEDx-YTT\\tedx-ytt-output.csv', ['Date', 'ID']), {}
2018-10-27 14:13:30,219 INFO Loading old data from C:\Users\Julian\GitHub\TEDx-YTT\tedx-ytt-output.csv
2018-10-27 14:13:30,226 INFO ...done!
2018-10-27 14:13:30,227 INFO TRACE: Calling load_data() with ('C:\\Users\\Julian\\GitHub\\TEDx-YTT\\tedx-ytt-statistics.csv', ['Date', 'Metric']), {}
2018-10-27 14:13:30,227 INFO Loading old data from C:\Users\Julian\GitHub\TEDx-YTT\tedx-ytt-statistics.csv
2018-10-27 14:13:30,248 INFO ...done!
2018-10-27 14:13:30,248 INFO Saving data ...
2018-10-27 14:13:30,257 INFO ...done!
2018-10-27 14:13:30,257 INFO Saving config ...
2018-10-27 14:13:30,259 INFO ...done!
